sudo: required

language: python
python:
  - "3.6"

services:
  - docker

before_install:
 - docker build -t stklik/crest .
script:
 - docker run stklik/crest /bin/sh -c "cd CREST; python -m unittest -v"
