sudo: required

language: python

services:
  - docker

before_install:
- docker build -t stklik/crest .
- docker run stklik/crest /bin/sh -c "cd CREST; python -m unittest -v"

script:
- python -m unittest -v
