sudo: required

language: python
python:
  - "3.6"

services:
  - docker

# build the docker
# install the codecov python tool to upload the things to the correct places
before_install:
 - docker build -t stklik/crest .

script:
  # pass travis environment info into the docker container
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  # run the tests inside the docker using coverage, also print coverage
  - docker run $ci_env stklik/crest
      /bin/bash -c 'pip install coverage;coverage run --source src --branch --omit */test_* -m unittest discover -v;coverage report;bash <(curl -s https://codecov.io/bash)'
